version: "3.8"

services:
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react
    command: npm start
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - 3000:3000
    networks:
      - ctf
  django:
    env_file:
      - ./backend/.env
    environment:
      - MODE=dev
      - DB_HOST=pgdb
      - DB_PORT=5432
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: django
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    command: /bin/sh -c "pip-compile --quiet requirements/base.in && pip install -r requirements/base.txt -q && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    networks:
      - ctf
  pgdb:
    env_file:
      - ./backend/.env
    image: postgres
    container_name: pgdb
    shm_size: 1g
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD={DB_PASSWORD}
    volumes:
      - ./database/:/database
      - pgdata:/var/lib/postgresql/data/
    networks:
      - ctf

volumes:
  pgdata:
    driver: local
  node-modules:
    driver: local

networks:
  ctf:
    driver: bridge
