version: "3.8"

services:
  react:
    extends:
      file: docker-compose.yml
      service: react
  django:
    extends:
      file: docker-compose.yml
      service: django
    depends_on:
      - pgdb
      - elasticsearch
  pgdb:
    extends:
      file: docker-compose.yml
      service: pgdb
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: es01
    restart: always
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elsdata:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  pgdata:
    driver: local
  node-modules:
    driver: local
  elsdata:
    driver: local

networks:
  elastic:
    driver: bridge
