version: "3.8"

services:
  react:
    build: ./frontend
    container_name: react
    command: npm start
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - 3000:3000
    networks:
      - ctf
  django:
    build: ./backend
    container_name: django
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    command: /bin/sh -c "pip-compile --quiet && pip install -r requirements.txt -q && python manage.py migrate && pip list && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    networks:
      - ctf
  pgdb:
    env_file:
      - ./backend/core/.env
    image: postgres
    container_name: pgdb
    shm_size: 1g
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD={DB_PASSWORD}
    volumes:
      - ./database/:/database
      - pgdata:/var/lib/postgresql/data/
    networks:
      - ctf

volumes:
  pgdata:
    driver: local
  node-modules:
    driver: local

networks:
  ctf:
    driver: bridge
