FROM python:3.8-alpine3.11

ARG USER=django-user

ENV PYTHONUNFUFFERED=1
ENV MODE=$MODE
ENV DJANGO_SECRET=$DJANGO_SECRET
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_PASSWORD=$DB_PASSWORD

RUN set -ex && apk --no-cache add sudo

# Add user and set up passwordless sudo
RUN adduser -D $USER \
    && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
    && chmod 0440 /etc/sudoers.d/$USER

WORKDIR /usr/src/app

# Copy application files over
COPY . .

# Grant user application file permissions and start running as user
RUN chown -R $USER /usr/src/app
USER $USER

# Make sure pip-compile and pip-sync are on PATH
ENV PATH "$PATH:/home/django-user/.local/bin"

# Install GCC (Alpine uses musl but we compile and link dependencies with GCC)
RUN sudo apk add --no-cache --virtual .build-deps gcc musl-dev \
    && sudo apk add uwsgi-python3 \
    && sudo apk add linux-headers \
    && sudo apk add postgresql-dev \
    && pip install --no-cache-dir pip-tools \
    && pip-compile requirements/base.in \
    && pip install --no-cache-dir -r requirements/base.txt \
    && sudo apk del .build-deps
