name: python build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  python-lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install black
      - run: black backend --check
      - run: black cdk --check
      - run: pip install flake8
      - run: flake8 backend
      - run: flake8 cdk
  django-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pytest
        run: pip install -r requirements.txt
        working-directory: backend
      - run: pytest tests
        env:
          DJANGO_SECRET: fake-secret
        working-directory: backend